import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/common/navbar";
import Providers from "@/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Providers>
        <body>
          <Navbar />
          <main className="p-3">
            {children}
          </main>
        </body>
      </Providers>
    </html>
  );
}
