import type { Metadata } from "next";
import "./globals.css";
import Providers from "@/providers";
import { Roboto  } from 'next/font/google'

const montserrat = Roboto ({
  subsets: ['greek'],
  weight: '500',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <body>
        <Providers>
          <main >
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
